### ISSUE TITLE
Пересечение отрезков

### ISSUE THREAD

**Issue by sergevkim** [gurovic/vgeome#7]
Добавить в класс Отрезок функцию "Пересечение отрезков". Обозначить значком &(**and**).

**Comment by sergevkim** [comment]
https://github.com/gurovic/vgeome/issues/11

**Comment by sergevkim** [comment]
Миша, скинь код на pastebin и ссылку этого кода сюда, в комментарии

**Comment by ragarg** [comment]
http://pastebin.com/pAQWBAnL

**Comment by ragarg** [comment]
все написано!
